-- VHDL Entity Test_Github_lib.TOP.symbol
--
-- Created:
--          by - adprda2.UNKNOWN (MD2D3GRC)
--          at - 15:08:03 01.08.2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2023.3 Built on 9 Jul 2023 at 00:00:47
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY TOP IS
   PORT( 
      clk  : IN     std_logic;
      d    : IN     std_logic;
      edge : OUT    std_logic
   );

-- Declarations

END TOP ;

--
-- VHDL Architecture Test_Github_lib.TOP.struct
--
-- Created:
--          by - adprda2.UNKNOWN (MD2D3GRC)
--          at - 15:08:03 01.08.2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2023.3 Built on 9 Jul 2023 at 00:00:47
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY Test_Github_lib;

ARCHITECTURE struct OF TOP IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT edge_detector
   PORT (
      clk  : IN     std_logic;
      d    : IN     std_logic;
      edge : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : edge_detector USE ENTITY Test_Github_lib.edge_detector;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : edge_detector
      PORT MAP (
         clk  => clk,
         d    => d,
         edge => edge
      );

END struct;
